version: '2'

networks:
  proxy-net:
    external: true

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
      - /etc/nginx/dhparam
      - /usr/share/nginx/html
    networks:
      - proxy-net
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes_from:
      - reverse-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ./docker/nginx-gen/templates:/etc/docker-gen/templates
    depends_on:
      - reverse-proxy
    networks:
      - proxy-net
    command: -notify-sighup reverse-proxy -watch /etc/docker-gen/templates/nginx2.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes_from:
      - reverse-proxy
    volumes:
      - /etc/acme.sh
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - reverse-proxy
    environment:
      DEFAULT_EMAIL: info@roscable.net
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: reverse-proxy
    networks:
      - proxy-net