version: '3.2'

networks:
  proxy-net:
    external: true

services:

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/default.conf"
    networks:
      - proxy-net

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
#    volumes_from:
#      - reverse-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ./docker/nginx-gen/templates:/etc/docker-gen/templates
    depends_on:
      - reverse-proxy
    networks:
      - proxy-net
    command: docker-gen -notify-sighup reverse-proxy -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf